version: "3.7"

services:
  store-api-db:
    image: postgres:14.1
    container_name: store-api-db
    restart: always
    env_file:
      - ./variables.env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - store-api-net-db
    ports:
      - "5432:5432"
    volumes:
      - store-api-vol-db:/var/lib/postgresql/data

networks:
  store-api-net-db:
    name: store-api-net-db

volumes:
  store-api-volume-db:
    name: store-api-vol-db
